spring:
  application:
    name: Shnurok

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: DaiMneSil1
    url: jdbc:mysql://localhost:3306/labsdb
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
